services:
    laravel.api:
        build:
            context: ./vendor/laravel/sail/runtimes/8.4
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: sail-8.4/app
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        expose:
            - '80'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
            IGNITION_LOCAL_SITES_PATH: '${PWD}'
            VIRTUAL_HOST: api.yourdomain.test
            VIRTUAL_PORT: 80
        volumes:
            - '.:/var/www/html'
        networks:
            - sail

    vue.app:
        image: node:latest
        working_dir: /var/www/html/user_interface
        volumes:
            - '.:/var/www/html'
        ports:
            - "3000:3000"
        command: sh -c "npm install && npm run serve"
        environment:
            VIRTUAL_HOST: yourdomain.test
            VIRTUAL_PORT: 3000
        networks:
            - sail

    nginx-proxy:
        image: jwilder/nginx-proxy
        ports:
            - "8080:80"
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:ro
        networks:
            - sail

networks:
    sail:
        driver: bridge
