unset APP_NAME
unset APP_ENV
unset APP_KEY
unset APP_DEBUG
unset APP_URL
unset FRONTEND_URL
unset SESSION_DOMAIN
unset SANCTUM_STATEFUL_DOMAINS

unset LOG_CHANNEL
unset LOG_DEPRECATIONS_CHANNEL
unset LOG_LEVEL

unset DB_CONNECTION
unset DB_HOST
unset DB_PORT
unset DB_DATABASE
unset DB_USERNAME
unset DB_PASSWORD

unset BROADCAST_DRIVER
unset CACHE_DRIVER
unset FILESYSTEM_DISK
unset QUEUE_CONNECTION
unset SESSION_DRIVER
unset SESSION_LIFETIME

unset MEMCACHED_HOST

unset REDIS_HOST
unset REDIS_PASSWORD
unset REDIS_PORT

unset MAIL_MAILER
unset MAIL_HOST
unset MAIL_PORT
unset MAIL_USERNAME
unset MAIL_PASSWORD
unset MAIL_ENCRYPTION
unset MAIL_FROM_ADDRESS
unset MAIL_FROM_NAME

unset AWS_ACCESS_KEY_ID
unset AWS_SECRET_ACCESS_KEY
unset AWS_DEFAULT_REGION
unset AWS_BUCKET
unset AWS_USE_PATH_STYLE_ENDPOINT

unset PUSHER_APP_ID
unset PUSHER_APP_KEY
unset PUSHER_APP_SECRET
unset PUSHER_HOST
unset PUSHER_PORT
unset PUSHER_SCHEME
unset PUSHER_APP_CLUSTER

unset VITE_APP_NAME
unset VITE_PUSHER_APP_KEY
unset VITE_PUSHER_HOST
unset VITE_PUSHER_PORT
unset VITE_PUSHER_SCHEME
unset VITE_PUSHER_APP_CLUSTER
